### PR TITLE
test: preview

### PR DESCRIPTION
**Pull request by xrkffgg**
I'm doing a test and will close a little bit.

### CODE REVIEW

**Comment by xrkffgg** [comment]
@afc163 @kerm1it 这好像没预览成功呢

我试了几个都不行，预览界面还保持原状

https://github.com/ant-design/pro-components/pull/923
https://github.com/zoo-js/zoo-issue-helper/pull/51
https://github.com/ant-design-colorful/ant-design-colorful/pull/18

**Comment by xrkffgg** [comment]
我用法不对？

**Comment by afc163** [comment]
@xrkffgg 貌似确实有问题，pull_request_target 指向了原始分支。

cc @shaodahong

**Comment by shaodahong** [comment]
一个已知的问题，https://github.com/actions/checkout/pull/321

对于 PR 来说可以尝试这个方案
https://github.com/actions/checkout/blob/f16eddee8410930a20309c41063631c4177643a5/README.md#checkout-pull-request-on-pull_request_target

**Comment by xrkffgg** [comment]
https://github.com/zoo-js/zoo-issue-helper/pull/54

加上这个可以了

with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

**Comment by afc163** [comment]
能在 surge_preview 里解决么？不然又要发一堆 PR 了：

https://github.com/ant-design/ant-design/pull/27453

image

**Comment by xrkffgg** [comment]
感觉不需用 push 触发啊

image

**Comment by shaodahong** [comment]
应该不行，还没到 `surge_preview` 这一步，其他的仓库暂时先不动，改这个库试试，后续没问题我来提 PR 吧

**Comment by xrkffgg** [comment]
push 检测了 build 正常，生成不了 url 来预览呢

**Pull request closed without merging**
